### ISSUE TITLE
jTox CRASH on a conversation

### ISSUE THREAD

**Issue by ghost** [almindor/harbour-jTox#35] opened 2017-05-02 19:24 UTC
JTOX crash on a conversation Suddenly when sending a message the message  that crash sends it well. But then when I start the app again. it puts that message that crash in the mode of sending without connection when it has already been sent before the crash, then that message is visualized sending without connection, and never send it again. Being the other friend active. Even if you send it before the crash

**Comment by almindor** [comment] 2017-05-04 00:41
This is a bit confusing so bear with me.

As I understand it you:

1. Send a message to an online friend and it crashes the app.
2. Restart the app and the message is in "offline/sending" mode, but it has also been received by the recipient.

Is this correct? Also, does it always happen?

**Comment by almindor** [comment] 2017-05-04 01:10
Moving to 2.0.0+ as I cannot reproduce right now...

**Closed as completed** 2017-05-04 15:36 UTC
Labels: bug

**Comment by ghost** [comment] 2017-05-04 19:26
1. Send a message to an online friend and it crashes the app.  > >  Sometimes. 
2. Restart the app and the message is in "offline/sending" mode, but it has also been received by the recipient. > > Yes.

# Fixed
